<?php
// config/settings.php
return array (
  'PAYSTACK_SECRET' => 'sk_test_da5c263e9f533087fe3a2600cd015b7ac00b33a5',
  'PAYSTACK_PUBLIC' => 'pk_test_f0959537bd47558aa8bc53c654090c20763f90b6',
  'PAYSTACK_DEFAULT_ACCOUNT' => '3003728830',
  'PAYSTACK_DEFAULT_BANK' => 'Kuda Bank',
  'PAYSTACK_DEFAULT_ACCOUNT_NAME' => 'Abstech Integrated Services',
  'MANUAL_DEPOSIT_ENABLED' => true,
  'CRYPTO_DEPOSIT_ENABLED' => true,
  'DEFAULT_PLAN_IMAGE' => '/assets/images/default-plan.svg',
  'REFERRAL_BONUS_AMOUNT' => 250.0,
  'MIN_WITHDRAWAL_AMOUNT' => 2000.0,
  'APP_NAME' => 'BitWealthBuilder',
  'APP_ALIAS' => 'BitW',
  'DASHBOARD' => 
  array (
    'BRAND' => 'BITW',
    'WELCOME_PREFIX' => 'Welcome back',
    'RANK_LABEL' => 'Current Rank',
    'RANK_LEVEL_PREFIX' => 'Level',
    'WALLET_BALANCE_LABEL' => 'Wallet Balance',
    'ACTIVE_MINING_LABEL' => 'Active Mining',
    'REFERRAL_EARNINGS_LABEL' => 'Referral Earnings',
    'ACTIVE_MINING_PLANS_LABEL' => 'Active Mining Plans',
    'RECENT_ACTIVITY_LABEL' => 'Recent Activity',
    'NO_ACTIVE_MINING_TEXT' => 'You have no active mining plans.',
    'BROWSE_PLANS_TEXT' => 'Browse Plans',
    'NO_NOTIFICATIONS_TEXT' => 'No notifications yet.',
    'VIEW_REFERRALS_TEXT' => 'View Referrals →',
    'PLANS_RUNNING_TEXT' => 'Plans Running',
    'DEPOSIT_TEXT' => 'Deposit',
    'WITHDRAW_TEXT' => 'Withdraw',
    'LOGOUT_TEXT' => 'Logout',
    'CLAIM_BUTTON_TEXT' => 'Claim Today',
    'CLAIM_CONFIRM_MESSAGE' => 'Claim mining earnings for this session?',
    'CLAIM_SUCCESS_MESSAGE' => 'Claim successful!',
    'CLAIM_FAILED_MESSAGE' => 'Claim failed',
    'DAILY_EARNING_LABEL' => 'Daily',
    'CURRENCY_SYMBOL' => '₦',
    'NAV_DASHBOARD' => 'Dashboard',
    'NAV_MINING' => 'Mining',
    'NAV_REFERRALS' => 'Referrals',
    'NAV_TRANSACTIONS' => 'Transactions',
    'NAV_WITHDRAW' => 'Withdraw',
    'NAV_SETTINGS' => 'Settings',
    'TITLE_PREFIX' => 'Dashboard',
  ),
);
